var kh_labels="S->LS S->L L->t L->dFd F->dFd F->LS".split(" "),nuc_labels=["A","C","G","U"],bp_a_labels=["AA","AC","AG","AU"],bp_c_labels=["CA","CC","CG","CU"],bp_g_labels=["GA","GC","GG","GU"],bp_u_labels=["UA","UC","UG","UU"],group_by_value=1,graph_width=20,graph_height=80,switch_button_text="Group by training set",chartCount=0;function switch_grouping(){switch_button_text=group_by_value?"Group by value":"Group by training set";group_by_value=!group_by_value;generate_graphs()}
function change_size(b,a){graph_width=b;graph_height=a;generate_graphs()}function change_size2(b,a){5<graph_width+b&&(graph_width+=b);20<graph_height+a&&(graph_height+=a);generate_graphs()}function generate_graphs(){generate_bar_plot()}
function generate_bar_plot(){var b=[],a=[],c=[],f=[],d=[],g=[],k=[],e,n;if(group_by_value){for(e=0;e<kh_arr.length;e++)for(var j in trainingSets)b.push({time:n++,value:trainingSets[j].grammar.prob.kh[kh_arr[e]],color:trainingSets[j].color});for(e=0;e<nuc_arr.length;e++)for(j in trainingSets)a.push({time:n++,value:trainingSets[j].grammar.prob.nuc[e],color:trainingSets[j].color});for(e=0;e<nuc_arr.length;e++)for(j in trainingSets)c.push({time:n++,value:trainingSets[j].grammar.prob.upn[e],color:trainingSets[j].color});
for(e=0;e<nuc_arr.length;e++)for(j in trainingSets)f.push({time:n++,value:trainingSets[j].grammar.prob.bp[A][e],color:trainingSets[j].color});for(e=0;e<nuc_arr.length;e++)for(j in trainingSets)d.push({time:n++,value:trainingSets[j].grammar.prob.bp[C][e],color:trainingSets[j].color});for(e=0;e<nuc_arr.length;e++)for(j in trainingSets)g.push({time:n++,value:trainingSets[j].grammar.prob.bp[G][e],color:trainingSets[j].color});for(e=0;e<nuc_arr.length;e++)for(j in trainingSets)k.push({time:n++,value:trainingSets[j].grammar.prob.bp[U][e],
color:trainingSets[j].color})}else{for(j in trainingSets)for(e=0;e<kh_arr.length;e++)b.push({time:n++,value:trainingSets[j].grammar.prob.kh[kh_arr[e]],color:trainingSets[j].color});for(j in trainingSets)for(e=0;e<nuc_arr.length;e++)a.push({time:n++,value:trainingSets[j].grammar.prob.nuc[e],color:trainingSets[j].color});for(j in trainingSets)for(e=0;e<nuc_arr.length;e++)c.push({time:n++,value:trainingSets[j].grammar.prob.upn[e],color:trainingSets[j].color});for(j in trainingSets)for(e=0;e<nuc_arr.length;e++)f.push({time:n++,
value:trainingSets[j].grammar.prob.bp[A][e],color:trainingSets[j].color});for(j in trainingSets)for(e=0;e<nuc_arr.length;e++)d.push({time:n++,value:trainingSets[j].grammar.prob.bp[C][e],color:trainingSets[j].color});for(j in trainingSets)for(e=0;e<nuc_arr.length;e++)g.push({time:n++,value:trainingSets[j].grammar.prob.bp[G][e],color:trainingSets[j].color});for(j in trainingSets)for(e=0;e<nuc_arr.length;e++)k.push({time:n++,value:trainingSets[j].grammar.prob.bp[U][e],color:trainingSets[j].color})}e=
$("#barGraph");e.html("");e.append("<button onclick='change_size2(-5,0);'><span>Width--<span></button>");e.append("<button onclick='change_size2(5,0);'><span>Width++<span></button>");e.append("<button onclick='change_size2(0,-5);'><span>Height--<span></button>");e.append("<button onclick='change_size2(0,5);'><span>Height++<span></button>");e.append("<button onclick='change_size(20,80);'><span>Sm<span></button>");e.append("<button onclick='change_size(30,120);'><span>Med<span></button>");e.append("<button onclick='change_size(40,160);'><span>Lg<span></button><br />");
e.append("<p><button id='switch_bttn' onclick='switch_grouping();'><span id='switch_text'>"+switch_button_text+"<span></button></p>");e.append("<h3>Knudsen-Hein Probabilities</h3>");format_chart(b,kh_labels,!0,"#barGraph");e.append("<h3>Nucleotide Distribution Probabilities</h3>");format_chart(a,nuc_labels,!1,"#barGraph");e.append("<h3>Unpaired Nucleotide Probabilities</h3>");format_chart(c,nuc_labels,!1,"#barGraph");e.append("<h3>Basepair A* Probabilities</h3>");format_chart(f,bp_a_labels,!0,"#barGraph");
e.append("<h3>Basepair C* Probabilities</h3>");format_chart(d,bp_c_labels,!0,"#barGraph");e.append("<h3>Basepair G* Probabilities</h3>");format_chart(g,bp_g_labels,!0,"#barGraph");e.append("<h3>Basepair U* Probabilities</h3>");format_chart(k,bp_u_labels,!0,"#barGraph")}
function format_chart(b,a,c,f){var d=graph_width,g=graph_height,k=d3.scale.linear().domain([0,1]).range([20,20+d]),e=d3.scale.linear().domain([0,1]).rangeRound([0,g]),n=d3.scale.linear().domain([1,0]).rangeRound([0,g]),j=0,f=d3.select(f).append("svg").attr("class","chart").attr("width",d*b.length-1+2*d+35).attr("height",g+40).attr("id","chart"+chartCount++);f.append("line").attr("x1",d).attr("x2",d*b.length+20).attr("y1",g+10).attr("y2",g+10).style("stroke","#000");f.append("line").attr("x1",18).attr("x2",
18).attr("y1",10).attr("y2",g+10).style("stroke","#000");j=f.append("g");j=j.selectAll(".rule").data(e.ticks(4)).enter().append("g").attr("class","rule").attr("transform",function(a){return"translate(0,"+(n(a)+10)+")"});j.append("line").attr("x1",15).attr("x2",d*b.length+20).style("stroke","#000");j.append("text").attr("x",0).attr("dy",".35em").text(function(a){return a});f.selectAll("rect").data(b).enter().append("rect").attr("x",function(a,f){return k(f)-0.5}).attr("y",function(a){return g-e(a.value)+
8}).attr("val",function(a){return a.value}).attr("width",d).attr("height",function(a){return e(a.value)}).attr("fill",function(a){return a.color}).attr("onmouseover","displayY();").attr("onmouseout","hideY();");if(group_by_value){b=b.length/a.length*d;for(j=0;j<a.length;j++){var m=25+d/2+j*b,o=g+5;f.append("text").attr("y",o+15).attr("x",m-(c?0:d/2)).attr("transform",c?"rotate(45, "+m+","+o+")":"").text(a[j])}}else for(j=0;j<b.length;j++)m=25+d/2+j*d,o=g+5,f.append("text").attr("y",o+15).attr("x",
m-(c?0:d/2)).attr("transform",c?"rotate(45, "+m+","+o+")":"").text(a[j%a.length])}
function getRGB(b){var a;if(a=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(b))return[parseInt(a[1]),parseInt(a[2]),parseInt(a[3])];if(a=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(b))return[2.55*parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3])];if(a=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(b))return[parseInt(a[1],16),parseInt(a[2],16),parseInt(a[3],16)];if(a=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(b))return[parseInt(a[1]+
a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16)]}function displayY(){var b=window.event;b&&(updateY(b),$(b.target).mousemove(updateY))}function updateY(b){if(b){var a=$("#posText");a&&a.remove();var c="#"+b.target.parentElement.id,a=$(c),f;f=b.pageX-a.position().left;a=b.pageY-a.position().top;d3.select(c).append("text").attr("id","posText").attr("x",f).attr("y",a-20).text($(b.target).attr("val"))}}function hideY(){var b=$("#posText");b&&b.remove();$(document).mousemove()}
var A=0,C=1,G=2,U=3,nuc_arr=[A,C,G,U],S=0,S_LS=1,S_L=2,L=3,L_t=4,L_dFd=5,F=6,F_dFd=7,F_LS=8,kh_arr=[S_LS,S_L,L_t,L_dFd,F_dFd,F_LS],NUN=0,NBP=0,num_dec=3;function TrainingSet(b,a,c,f){this.ele=b;this.name=a;this.sequences=c?c:{};this.color=f?f:"#FFF";this.add=function(a){a&&$(a.ele).attr("id")&&(a.seq&&a.str)&&(this.sequences[$(a.ele).attr("id")]=a)};this.remove=function(a){this.sequences[a]&&(delete sequences[a],resetLists())};this.clear=function(){this.sequences=[]}}
function Sequence(b,a,c,f){this.ele=b;this.name=a;this.seq=c;this.str=f;this.output=function(){return this.name+": "+this.seq+" - "+this.str}}
function PfoldGrammar(b,a){this.name=b;this.seqs=a?a:[];this.counts={};this.counts.NUN=0;this.counts.NBP=0;this.counts.kh=[0,0,0,0,0,0,0,0,0];this.counts.nuc=[0,0,0,0];this.counts.upn=[0,0,0,0];this.counts.bp=[];for(var c=0;4>c;c++)this.counts.bp[c]=[0,0,0,0];this.prob={};this.prob.kh=[0,0,0,0,0,0,0,0,0];this.prob.nuc=[0,0,0,0];this.prob.upn=[0,0,0,0];this.prob.bp=[];for(c=0;4>c;c++)this.prob.bp[c]=[0,0,0,0];this.output=function(){var a="<b>"+this.name+" (probabilities):</b>\n\n",a=a+"Knudson-Hein:\n"+
("S->LS\t"+this.prob.kh[S_LS].toFixed(num_dec)+"\tS->L\t"+this.prob.kh[S_L].toFixed(num_dec)),a=a+("\nL->t\t"+this.prob.kh[L_t].toFixed(num_dec)+"\tL->dFd\t"+this.prob.kh[L_dFd].toFixed(num_dec)),a=a+("\nF->dFd\t"+this.prob.kh[F_dFd].toFixed(num_dec)+"\tF->LS\t"+this.prob.kh[F_LS].toFixed(num_dec)),a=a+"\n\nPfold Unpaired Nucleotides:\nA\tC\tG\tU\n",d,b;for(d=0;4>d;d++)a+=this.prob.upn[d].toFixed(num_dec)+"\t";var a=a+"\n\nPfold Base Pairs:\n\tA\tC\tG\tU\n",c=["A","C","G","U"];for(d=0;4>d;d++){a+=
c[d]+"\t";for(b=0;4>b;b++)a+=this.prob.bp[d][b].toFixed(num_dec)+"\t";a+="\n"}a+="\n\nNucleotide Distribution:\nA\tC\tG\tU\n";for(d=0;4>d;d++)a+=this.prob.nuc[d].toFixed(num_dec)+"\t";return a};this.output_counts=function(){var a="<b>"+this.name+" (Counts):</b>\n\n",a=a+"Knudson-Hein Counts:\n"+("S->LS\t"+this.counts.kh[S_LS]+"\tS->L\t"+this.counts.kh[S_L]),a=a+("\nL->t\t"+this.counts.kh[L_t]+"\tL->dFd\t"+this.counts.kh[L_dFd]),a=a+("\nF->dFd\t"+this.counts.kh[F_dFd]+"\tF->LS\t"+this.counts.kh[F_LS]),
a=a+"\n\nPfold Unpaired Nucleotides Counts:\nA\tC\tG\tU\n",d,b;for(d=0;4>d;d++)a+=this.counts.upn[d]+"\t";var a=a+"\n\nPfold Base Pair Counts:\n\tA\tC\tG\tU\n",c=["A","C","G","U"];for(d=0;4>d;d++){a+=c[d]+"\t";for(b=0;4>b;b++)a+=this.counts.bp[d][b]+"\t";a+="\n"}a+="\n\nNucleotide Counts:\nA\tC\tG\tU\n";for(d=0;4>d;d++)a+=this.counts.nuc[d]+"\t";return a};this.csv_counts=function(){var a=this.name+"\n",a=a+"Knudson-Hein:\nS->LS,\tS->L,\tL->t,\tL->dFd,\tF->dFd,\tF->LS\n"+(this.counts.kh[S_LS]+",\t"+
this.counts.kh[S_L]+",\t"+this.counts.kh[L_t]+",\t"),a=a+(this.counts.kh[L_dFd]+",\t"+this.counts.kh[F_dFd]+",\t"+this.counts.kh[F_LS]),a=a+"\nPfold Unpaired Nucleotides:\nA,\tC,\tG,\tU\n",b;for(b=0;3>b;b++)a+=this.counts.upn[b]+",\t";a+=this.counts.upn[3];a+="\nPfold Base Pair:\nAA,\tAC,\tAG,\tAU\n";for(b=0;3>b;b++)a+=this.counts.bp[A][b]+",\t";a+=this.counts.bp[A][3];a+="\nCA,\tCC,\tCG,\tCU\n";for(b=0;3>b;b++)a+=this.counts.bp[C][b]+",\t";a+=this.counts.bp[C][3];a+="\nGA,\tGC,\tGG,\tGU\n";for(b=
0;3>b;b++)a+=this.counts.bp[G][b]+",\t";a+=this.counts.bp[G][3];a+="\nUA,\tUC,\tUG,\tUU\n";for(b=0;3>b;b++)a+=this.counts.bp[U][b]+",\t";a+=this.counts.bp[U][3];a+="\nNucleotide Distribution:\nA,\tC,\tG,\tU\n";for(b=0;3>b;b++)a+=this.counts.nuc[b]+",\t";return a+this.counts.nuc[3]}}
function Expectations(b){this.grammar=b;this.ExECD=this.ExEH=this.ExR5=this.ExR4=this.ExR3=this.ExM=this.ExI=this.ExLb=this.ExHp=this.ExBp=this.ExH=this.rho=0;this.calculate=function(){getExpectations(this);return this};this.output=function(){var a="RNA Motif Expectations for "+this.grammar.name+"\n\n\t",a=a+("\\rho_0 = "+this.rho),a=a+("\n\n\tHelices: "+this.ExH),a=a+(" * n\n\n\tBasepairs: "+this.ExBp),a=a+(" * n\n\n\tHairpin Loops: "+this.ExHp),a=a+(" * n\n\n\tBulge Loops: "+this.ExLb),a=a+(" * n\n\n\tInternal: "+
this.ExI),a=a+(" * n\n\n\tMulti-Loops: "+this.ExM),a=a+(" * n\n\n\tMulti-Loops (degree 3): "+this.ExR3),a=a+(" * n\n\n\tMulti-Loops (degree 4): "+this.ExR4),a=a+(" * n\n\n\tMulti-Loops (degree 5): "+this.ExR5),a=a+(" * n\n\n\tHelices in External Loop: "+this.ExEH);return a+(" * n\n\n\t5'-3' Distance in External Loop: "+this.ExECD+"* n")}}
function train_grammar(b){var a=new PfoldGrammar(b.name,b.sequences);NBP=NUN=0;for(var c in b.sequences){var f=b.sequences[c],d=getPairsArraySt(f.str);train_on_sequences_kh(f.str,d,0,f.str.length-1,!1,a.counts.kh);train_on_sequences_pf(f.seq,f.str,d,a)}a.counts.NUN=NUN;a.counts.NBP=NBP;a.counts.kh[L_t]+=NUN;a.counts.kh[F]+=NBP;a.counts.kh[S]=a.counts.kh[S_L]+a.counts.kh[S_LS];a.counts.kh[L]=a.counts.kh[L_t]+a.counts.kh[F]-a.counts.kh[F_dFd];a.counts.kh[F_LS]=a.counts.kh[F]-a.counts.kh[F_dFd];a.prob.kh[S]=
1;a.prob.kh[S_L]=a.counts.kh[S_L]/a.counts.kh[S];a.prob.kh[S_LS]=a.counts.kh[S_LS]/a.counts.kh[S];a.prob.kh[L]=1;a.prob.kh[L_t]=a.counts.kh[L_t]/a.counts.kh[L];a.prob.kh[L_dFd]=a.counts.kh[L_dFd]/a.counts.kh[L];a.prob.kh[F]=1;a.prob.kh[F_dFd]=a.counts.kh[F_dFd]/a.counts.kh[F];a.prob.kh[F_LS]=a.counts.kh[F_LS]/a.counts.kh[F];for(b=c=0;4>b;b++)c+=a.counts.nuc[b];for(b=0;4>b;b++)a.prob.nuc[b]=a.counts.nuc[b]/c;for(b=c=0;4>b;b++)c+=a.counts.upn[b];for(b=0;4>b;b++)a.prob.upn[b]=a.counts.upn[b]/c;for(b=
c=0;4>b;b++)for(f=0;4>f;f++)c+=a.counts.bp[b][f];for(b=0;4>b;b++)for(f=0;4>f;f++)a.prob.bp[b][f]=a.counts.bp[b][f]/c;return a}function train_on_sequences_kh(b,a,c,f,d,g){if(!(c>f||c>=b.length))for(;c<=f;c++){var k=b.charAt(c);"."==k?c==f?g[S_L]++:d&&g[S_LS]++:"("==k&&(d&&(a[c]==f?g[S_L]++:g[S_LS]++),0<c&&a[c-1]==a[c]+1?g[F_dFd]++:g[L_dFd]++,train_on_sequences_kh(b,a,c+1,a[c]-1,!1,g),c=a[c]);d=!0}}
function train_on_sequences_pf(b,a,c,f){for(var d=getNucleotideIndexArray(b),g,k=0;k<b.length;k++)switch(g=a.charAt(k),f.counts.nuc[d[k]]++,f.counts.nuc[4]++,g){case ".":f.counts.upn[d[k]]++;f.counts.upn[4]++;break;case "(":f.counts.bp[d[k]][d[c[k]]]++}}function getPairsArraySt(b){for(var a=[],c=[],f=b.length,d=0;d<f;d++){c[d]=-1;var g=b.charAt(d);"("==g?(a.push(d),NBP++):")"==g?(c[d]=a.pop(),c[c[d]]=d):NUN++}return c}
function getNucleotideIndexArray(b){for(var b=b.toUpperCase(),a=[],c,f=0;f<b.length;f++)switch(c=b.charAt(f),c){case "A":a[f]=A;break;case "C":a[f]=C;break;case "G":a[f]=G;break;case "U":a[f]=U;break;default:a[f]=-1}return a}var MAXDEGREE=100,MDP1=MAXDEGREE+1;function QuadSD_ak1(b,a,c,f,d,g){d[0]=g.b=f[0];d[1]=g.a=-(a*g.b)+f[1];for(var k=2;k<b;k++)d[k]=-(a*g.a+c*g.b)+f[k],g.b=g.a,g.a=d[k]}
function calcSC_ak1(b,a,c,f,d,g,k,e,n){var j={},m=3;j.b=j.a=0;QuadSD_ak1(a,k,e,g,n,j);d.c=j.a;d.d=j.b;if(Math.abs(d.c)<=100*b*Math.abs(g[a-1])&&Math.abs(d.d)<=100*b*Math.abs(g[a-2]))return m;d.h=e*f;Math.abs(d.d)>=Math.abs(d.c)?(m=2,d.e=c/d.d,d.f=d.c/d.d,d.g=k*f,d.a3=d.e*(d.g+c)+d.h*(f/d.d),d.a1=-c+d.f*f,d.a7=d.h+(d.f+k)*c):(m=1,d.e=c/d.c,d.f=d.d/d.c,d.g=d.e*k,d.a3=d.e*c+(d.g+d.h/d.c)*f,d.a1=-(c*(d.d/d.c))+f,d.a7=d.g*d.d+d.h*d.f+c);return m}
function nextK_ak1(b,a,c,f,d,g,k,e,n){if(3==c){k[1]=k[0]=0;for(b=2;b<a;b++)k[b]=e[b-2]}else if(c=1==c?d:f,Math.abs(g.a1)>10*b*Math.abs(c)){g.a7/=g.a1;g.a3/=g.a1;k[0]=n[0];k[1]=-(n[0]*g.a7)+n[1];for(b=2;b<a;b++)k[b]=-(n[b-1]*g.a7)+e[b-2]*g.a3+n[b]}else{k[0]=0;k[1]=-(n[0]*g.a7);for(b=2;b<a;b++)k[b]=-(n[b-1]*g.a7)+e[b-2]*g.a3}}
function newest_ak1(b,a,c,f,d,g,k,e,n,j,m,o,l,r,p,h,i){a.b=a.a=0;if(3!=b&&(2!=b?(b=c+l*k+o*j,n=e+(l+r*j)*n):(b=(c+m)*j+o,n=(j+l)*e+r*n),e=-(p[h-1]/i[h]),p=-(p[h-2]+e*i[h-1])/i[h],h=e*g,d*=e*e,i=-(h+d)+r*p*f,b=-i+n+e*b,0!=b))a.a=-((l*(d+h)+r*(e*f+p*g))/b)+l,a.b=r*(1+i/b)}
function Quad_ak1(b,a,c,f){var d,g;f.sr=f.si=f.lr=f.li=0;0==b?f.sr=0!=a?-(c/a):f.sr:0==c?f.lr=-(a/b):(a/=2,Math.abs(a)<Math.abs(c)?(g=-(0<=c?b:-b)+a*(a/Math.abs(c)),d=Math.sqrt(Math.abs(g))*Math.sqrt(Math.abs(c))):(g=-(b/a*(c/a))+1,d=Math.sqrt(Math.abs(g))*Math.abs(a)),0<=g)?(f.lr=(-a+(0<=a?-d:d))/b,f.sr=0!=f.lr?c/f.lr/b:f.sr):(f.lr=f.sr=-(a/b),f.si=Math.abs(d/b),f.li=-f.si)}
function QuadIT_ak1(b,a,c,f,d,g,k,e,n,j,m,o){var l={},r,p,h,i,q,t,v,s=0,u=0;c.NZ=0;do{l.li=l.lr=l.si=l.sr=0;Quad_ak1(1,f,d,l);c.szr=l.sr;c.szi=l.si;c.lzr=l.lr;c.lzi=l.li;if(Math.abs(Math.abs(c.szr)-Math.abs(c.lzr))>0.01*Math.abs(c.lzr))break;QuadSD_ak1(k,f,d,n,g,e);p=Math.abs(-(c.szr*e.b)+e.a)+Math.abs(c.szi*e.b);v=Math.sqrt(Math.abs(d));r=2*Math.abs(g[0]);q=-(c.szr*e.b);for(t=1;t<a;t++)r=r*v+Math.abs(g[t]);r=r*v+Math.abs(q+e.a);r=(9*r+2*Math.abs(q)-7*(Math.abs(e.a+q)+v*Math.abs(e.b)))*b;if(p<=20*
r){c.NZ=2;break}s++;if(20<s)break;if(2<=s&&0.01>=i&&p>=h&&!u){i=i<b?Math.sqrt(b):Math.sqrt(i);f-=f*i;d+=d*i;QuadSD_ak1(k,f,d,n,g,e);for(t=0;5>t;t++)r=calcSC_ak1(b,a,e.a,e.b,m,o,f,d,j),nextK_ak1(b,a,r,e.a,e.b,m,o,j,g);u=1;s=0}h=p;r=calcSC_ak1(b,a,e.a,e.b,m,o,f,d,j);nextK_ak1(b,a,r,e.a,e.b,m,o,j,g);r=calcSC_ak1(b,a,e.a,e.b,m,o,f,d,j);newest_ak1(r,e,e.a,m.a1,m.a3,m.a7,e.b,m.c,m.d,m.f,m.g,m.h,f,d,o,a,n);p=e.a;t=e.b;0!=t&&(i=Math.abs((-d+t)/t),f=p,d=t)}while(0!=t)}
function RealIT_ak1(b,a,c,f,d,g,k,e,n){var j,m,o,l,r,p,h,i,q,t=f-1;a.NZ=q=h=0;for(p=c.a;;){c=d[0];k[0]=c;for(i=1;i<g;i++)k[i]=c=c*p+d[i];o=Math.abs(c);l=Math.abs(p);j=0.5*Math.abs(k[0]);for(i=1;i<g;i++)j=j*l+Math.abs(k[i]);if(o<=20*b*(2*j-o)){a.NZ=1;a.szr=p;a.szi=0;break}q++;if(10<q)break;if(2<=q&&Math.abs(m)<=0.001*Math.abs(-m+p)&&o>r){h=1;a.a=p;break}r=o;n[0]=m=e[0];for(i=1;i<f;i++)n[i]=m=m*p+e[i];if(Math.abs(m)>10*Math.abs(e[t])*b){m=-(c/m);e[0]=k[0];for(i=1;i<f;i++)e[i]=m*n[i-1]+k[i]}else{e[0]=
0;for(i=1;i<f;i++)e[i]=n[i-1]}m=e[0];for(i=1;i<f;i++)m=m*p+e[i];m=Math.abs(m)>10*Math.abs(e[t])*b?-(c/m):0;p+=m}return h}
function Fxshfr_ak1(b,a,c,f,d,g,k,e,n,j,m){var o={},l={},r=Array(MDP1),p=Array(MDP1),h,i,q,t,v,s,u,w,x,y,z,D,E,J,H=1,I,B,K;m.NZ=0;t=q=0.25;v=c;w=f;o.b=o.a=0;QuadSD_ak1(e,j,f,k,n,o);h=o.a;i=o.b;l.h=l.g=l.f=l.e=l.d=l.c=l.a7=l.a3=l.a1=0;B=calcSC_ak1(b,g,h,i,l,d,j,f,r);for(I=0;I<a;I++){J=1;nextK_ak1(b,g,B,h,i,l,d,r,n);B=calcSC_ak1(b,g,h,i,l,d,j,f,r);newest_ak1(B,o,h,l.a1,l.a3,l.a7,i,l.c,l.d,l.f,l.g,l.h,j,f,d,g,k);z=o.a;E=D=o.b;c=0!=d[g-1]?-(k[g]/d[g-1]):0;x=y=1;if(0!=I&&3!=B&&(y=0!=E?Math.abs((E-w)/E):
y,x=0!=c?Math.abs((c-v)/c):x,u=y<u?y*u:1,s=x<s?x*s:1,w=u<t?1:0,(v=s<q?1:0)||w)){for(i=0;i<g;i++)p[i]=d[i];h=c;for(B=K=0;;){if(!(J&&0==(J=0))||!v||w&&!(s<u)){QuadIT_ak1(b,g,m,z,D,n,e,o,k,r,l,d);if(0<m.NZ)return;H=K=1;t*=0.25;if(B||!v)H=0;else for(i=0;i<g;i++)d[i]=p[i]}if(0!=H){o.a=h;H=RealIT_ak1(b,m,o,g,k,e,n,d,r);h=o.a;if(0<m.NZ)return;B=1;q*=0.25;if(0!=H){z=-(h+h);D=h*h;continue}}for(i=0;i<g;i++)d[i]=p[i];if(!w||K)break}QuadSD_ak1(e,j,f,k,n,o);h=o.a;i=o.b;B=calcSC_ak1(b,g,h,i,l,d,j,f,r)}w=E;v=c;
u=y;s=x}}
function rpSolve(b){var a=b.elements,c="",f="",d=[],g=0,k=0,g=0,e,n=Array(MDP1);document.getElementById("output").innerHTML=f;b.erCode.value="";c+=a[0].value;if(0==c.length)alert("The length of textareaString is 0. No data has been entered. No further action taken.");else if(-1==c.search(/\d/))alert("textareaString does not contain any digits. No further action taken.");else if(-1!=c.search(/[^\d\.\s\+-]/))alert("textareaString contains an invalid character. Please edit data so that it is in the appropriate format. No further action taken.");else if(-1==
c.search(/\n/))alert("This utility requires more than two entries to be entered, but two entries have not been detected. Either fewer than two entries have been entered, or the data is not in the appropriate format. No further action taken.");else if(c=c.replace(/\s*$/,""),c=c.replace(/^\s*/,""),d=c.split(/\s+/g),g=d.length,3>g)alert("This utility requires AT LEAST three entries to be entered, but fewer than three entries have been detected. No further action taken.");else if(g>MDP1+1)alert("This utility accepts input of up to 102 entries: the first for the degree and up to 101 for the coefficients. However, more than 102 entries have been input. No further action taken.");
else if(k=g-1,c=parseInt(d[0]),isNaN(c))alert("Invalid input for polynomial degree. No further action taken");else if(g=c,g>MAXDEGREE)b.erCode.value=-1;else if(0>g)alert("Negative values for the polynomial degree are not accepted. No further action taken.");else if(g!=k-1)alert("The number of coefficients entered does not correspond with the polynomial degree input. Check the data. No further action taken.");else{c=1;for(a=0;a<k;a++){e=parseFloat(d[c]);c++;if(isNaN(e)){alert("Invalid input for entry "+
(a+1)+". No further action taken");return}n[a]=e}if(0==n[0])b.erCode.value=0;else{rpSolve2(g,n);b.erCode.value=g;b=f+="<br /> &nbsp; &nbsp; The zeros follow:<br /> &nbsp; &nbsp;";for(a=0;a<g;a++)f+=b.zeror[a],0!=b.zeroi[a]&&(f=f+" &nbsp; + &nbsp; "+b.zeroi[a]+" i"),f+="<br /> &nbsp; &nbsp;";document.getElementById("output").innerHTML=f}}}
function rpSolve2(b,a){var c=b,f=Math.LN2,d=Array(MAXDEGREE),g=Array(MAXDEGREE),k=Array(MDP1),e=Array(MDP1),n=Array(MDP1),j=Array(MDP1),m={},o={},l,r,p,h,i,q,t,v,s,u;p=1;do r=p,p/=2,t=1+p;while(1<t);var w=Number.MIN_VALUE/r,x=Math.cos(1.6406094968746698),y=Math.sin(1.6406094968746698),z=Math.sqrt(0.5),D=-z;o.NZ=s=0;for(o.szr=o.szi=o.lzr=o.lzi=0;0==a[c];)d[s]=g[s]=0,c--,s++;for(u=c+1;1<=c;){if(2>=c){2>c?(d[b-1]=-(a[1]/a[0]),g[b-1]=0):(m.li=m.lr=m.si=m.sr=0,Quad_ak1(a[0],a[1],a[2],m),d[b-2]=m.sr,g[b-
2]=m.si,d[b-1]=m.lr,g[b-1]=m.li);break}i=0;q=Number.MAX_VALUE;for(h=0;h<u;h++)l=Math.abs(a[h]),l>i&&(i=l),0!=l&&l<q&&(q=l);h=w/q;if(1>=h&&10<=i||1<h&&Number.MAX_VALUE/h>=i)if(h=0==h?Number.MIN_VALUE:h,i=Math.floor(Math.log(h)/f+0.5),i=Math.pow(2,i),1!=i)for(h=0;h<u;h++)a[h]*=i;for(h=0;h<u;h++)e[h]=Math.abs(a[h]);e[c]=-e[c];i=c-1;l=Math.exp((Math.log(-e[c])-Math.log(e[0]))/c);0!=e[i]&&(p=-e[c]/e[i],l=p<l?p:l);p=l;do{l=p;p=0.1*l;q=e[0];for(h=1;h<u;h++)q=q*p+e[h]}while(0<q);do{p=q=e[0];for(h=1;h<c;h++)q=
l*q+e[h],p=l*p+q;q=l*q+e[c];h=q/p;l-=h}while(0.005<Math.abs(h/l));for(h=1;h<c;h++)k[h]=(c-h)*a[h]/c;k[0]=a[0];p=a[c];t=a[i];v=0==k[i]?1:0;for(q=0;5>q;q++)if(h=k[i],v){for(h=0;h<i;h++)s=i-h,k[s]=k[s-1];k[0]=0;v=0==k[i]?1:0}else{v=-p/h;for(h=0;h<i;h++)s=i-h,k[s]=v*k[s-1]+a[s];k[0]=a[0];v=Math.abs(k[i])<=10*Math.abs(t)*r?1:0}for(h=0;h<c;h++)j[h]=k[h];for(q=1;20>=q;q++)if(i=-(y*D)+x*z,D=y*z+x*D,z=i,i=l*z,h=-(2*i),Fxshfr_ak1(r,20*q,i,l,k,c,a,u,n,h,o),0!=o.NZ){s=b-c;d[s]=o.szr;g[s]=o.szi;u-=o.NZ;c=u-1;
for(h=0;h<u;h++)a[h]=n[h];1!=o.NZ&&(d[s+1]=o.lzr,g[s+1]=o.lzi);break}else for(h=0;h<c;h++)k[h]=j[h];if(20<q)break}c={};c.zeror=d;c.zeroi=g;return c}
$(document).ready(function(){$.fn.drag_drop_multi_select.defaults.after_drop_action=function(b,a,c,f){$(f.target).find("ul").append(b)};$("#drag_drop").drag_drop_multi_select({element_to_drag_drop_select:".list ul li",elements_to_drop:".list",elements_to_cancel_select:".title"});$("#drag_drop .items_selected").JCSS_align({vertical_align:"bottom",horizontal_align:"left"});$(function(){$("#tabs").tabs()})});
function resetLists(){$.fn.drag_drop_multi_select.defaults.after_drop_action=function(b,a,c,f){$(f.target).find("ul").append(b);updateTrainingSets()};$("#drag_drop").drag_drop_multi_select({element_to_drag_drop_select:".list ul li",elements_to_drop:".list",elements_to_cancel_select:".title"});$("#drag_drop .items_selected").JCSS_align({vertical_align:"bottom",horizontal_align:"left"});updateTrainingSets()}
function updateTrainingSets(){for(var b in trainingSets){var a=trainingSets[b];a.clear();$(a.ele).find("ul li").each(function(){null==$(this).attr("ddms_drag")&&a.add(new Sequence($(this),$(this).text(),$(this).attr("seq"),$(this).attr("str")))})}$("#resultsText").html("Train the grammars to see results here");$("#resultsGraphs").html("Train the grammars to see results here")}
$(document).ready(function(){$.fn.drag_drop_multi_select.defaults.after_drop_action=function(b,a,c,f){$(f.target).find("ul").append(b)};$("#drag_drop").drag_drop_multi_select({element_to_drag_drop_select:".list ul li",elements_to_drop:".list",elements_to_cancel_select:".title"});$("#drag_drop .items_selected").JCSS_align({vertical_align:"bottom",horizontal_align:"left"});$(function(){$("#tabs").tabs()})});
function resetLists(){$.fn.drag_drop_multi_select.defaults.after_drop_action=function(b,a,c,f){$(f.target).find("ul").append(b);updateTrainingSets()};$("#drag_drop").drag_drop_multi_select({element_to_drag_drop_select:".list ul li",elements_to_drop:".list",elements_to_cancel_select:".title"});$("#drag_drop .items_selected").JCSS_align({vertical_align:"bottom",horizontal_align:"left"});updateTrainingSets()}
function updateTrainingSets(){for(var b in trainingSets){var a=trainingSets[b];a.clear();$(a.ele).find("ul li").each(function(){null==$(this).attr("ddms_drag")&&a.add(new Sequence($(this),$(this).text(),$(this).attr("seq"),$(this).attr("str")))})}$("#resultsText").html("Train the grammars to see results here");$("#resultsGraphs").html("Train the grammars to see results here")};